name: tp-lab-actions
run-name: ${{ github.actor }} is running TPLab04
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test project
      - uses: ./.github/actions/{path}
        with: 
          run: ./test.sh
